@TeacherControl.Api_HostAddress = http://localhost:5229

### Login
POST {{TeacherControl.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "TeacherControl123!"
}
